# Generated by Django 3.0.3 on 2020-03-19 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_item_todolist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
