# Generated by Django 3.0.3 on 2020-03-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='added_by',
        ),
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
    ]
