# Generated by Django 3.0.3 on 2020-03-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_task_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
    ]
